version: "3.3"
services:
  web:
    build: server
    ports:
      - "8080:8080"
    environment:
      SQL_USER: invoice_separation
      SQL_PASSWORD: invoice_separation
      SQL_DB: invoice_separation_db
      SQL_HOST: postgres
      SQL_PORT: 5432
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: invoice_separation
      POSTGRES_PASSWORD: invoice_separation
      POSTGRES_DB: invoice_separation_db
volumes:
  postgres_data:
