version: "3.3"
services:
  web:
    build: server
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    volumes:
      - ./api/api.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
