# coding: utf-8

# flake8: noqa
"""
    Invoice separation

    TODO  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.credentials import Credentials
from swagger_client.models.invoice_separation_request import InvoiceSeparationRequest
