# coding: utf-8

"""
    Invoice separation

    TODO  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class InvoiceSeparationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'invoice': 'int',
        'users': 'list[str]'
    }

    attribute_map = {
        'invoice': 'invoice',
        'users': 'users'
    }

    def __init__(self, invoice=None, users=None, _configuration=None):  # noqa: E501
        """InvoiceSeparationRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._invoice = None
        self._users = None
        self.discriminator = None

        if invoice is not None:
            self.invoice = invoice
        if users is not None:
            self.users = users

    @property
    def invoice(self):
        """Gets the invoice of this InvoiceSeparationRequest.  # noqa: E501

        Amount of money spent  # noqa: E501

        :return: The invoice of this InvoiceSeparationRequest.  # noqa: E501
        :rtype: int
        """
        return self._invoice

    @invoice.setter
    def invoice(self, invoice):
        """Sets the invoice of this InvoiceSeparationRequest.

        Amount of money spent  # noqa: E501

        :param invoice: The invoice of this InvoiceSeparationRequest.  # noqa: E501
        :type: int
        """

        self._invoice = invoice

    @property
    def users(self):
        """Gets the users of this InvoiceSeparationRequest.  # noqa: E501

        Users to split money between  # noqa: E501

        :return: The users of this InvoiceSeparationRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this InvoiceSeparationRequest.

        Users to split money between  # noqa: E501

        :param users: The users of this InvoiceSeparationRequest.  # noqa: E501
        :type: list[str]
        """

        self._users = users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvoiceSeparationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoiceSeparationRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InvoiceSeparationRequest):
            return True

        return self.to_dict() != other.to_dict()
